#==============================O==============================#
# I---------------------------------------------------------I #
# |         Pet Master 1.12.1 configuration - Readme        | #
# 1---------------------------------------------------------1 #
#==============================o==============================#

# For horses or llamas, it is recommended that the player right-clicks on the horse while sneaking.
# Only spaces, no tabs. To check your file, use: yaml-online-parser.appspot.com
# Default config.yml file: github.com/PyvesB/PetMaster/blob/master/src/main/resources/config.yml
# Visit the GitHub for some additional documentation: github.com/PyvesB/PetMaster

#=============================O=O=============================#
# II-------------------------------------------------------II #
# |                    General  settings                    | #
# 2---------------------------------------------------------2 #
#=============================o=o=============================#
  
# Enable or disable chat messages when right-clicking on a pet.
chatMessage: false

# Enable or disable hologram messages when right-clicking on a pet (requires Holographic Displays).
hologramMessage: false

# Enable or disable action bar messages when right-clicking on a pet.
actionBarMessage: true

# Duration of the hologram, in server ticks (20 ticks = 1 second).
hologramDuration: 50

# Show health next to owner in chat and action bar messages (not holograms).
showHealth: true

# Check for update on plugin launch and notify when an OP joins the game.
checkForUpdate: true

# Name of the language file.
languageFileName: 'lang.yml'

# Enable or disable showing ownership information for a player's own pets.
displayToOwner: false

# Price of the /petm setowner command (requires Vault, not charged if petmaster.admin permission).
changeOwnerPrice: 0

# Price of the /petm free command (requires Vault, not charged if petmaster.admin permission).
freePetPrice: 0

# Take dogs into account.
displayDog: true

# Take cats into account.
displayCat: true

# Take horses into account.
displayHorse: true

# Take llamas into account.
displayLlama: true

# Take parrots into account.
displayParrot: true

# Prevent others from using leash on pet.
disableLeash: false

# Prevent others from mounting pet (horse/donkey).
disableRiding: false

# Protect pets to avoid being hurt by other player.
disablePlayerDamage: false

# Allows players to defend themselves against angry tamed mobs (e.g. dogs) even if disablePlayerDamage is true.
enableAngryMobPlayerDamage: true

#=============================OOO=============================#
# III-----------------------------------------------------III #
# |         Parameters to appear in future versions         | #
# 3---------------------------------------------------------3 #
#=============================ooo=============================#